services:
  back:
    command: ["npm", "run", "start:prod"]
    healthcheck:
      test: wget -qO- --header='ignoreT:true' localhost:3000/api/casl-rule
      interval: 8s
      timeout: 15s
      retries: 20
      start_period: 70s
    env_file: !override
      - .env
      - ./minio/.env.minio
      - ./redis/.env.redis
      - .env.secrets
      - .env.prod.test

  front:
    image: harbor.hyvatech.com/maskan/front:test-production
    healthcheck:
      test: wget -qO- localhost:4200
      interval: 5s
      timeout: 15s
      retries: 20
      start_period: 20s
    # command: ["npm", "run", "serve:prod"]
  
  nginx:
    volumes: !override
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf


